-- MySQL Script generated by MySQL Workbench
-- Fri Nov  6 15:04:44 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_2` ;

-- -----------------------------------------------------
-- Table `db_2`.`Station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_2`.`Station` (
  `station_id` INT NOT NULL COMMENT '',
  `station_name` VARCHAR(45) NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  `postal_code` VARCHAR(45) NULL COMMENT '',
  `city` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`station_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_2`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_2`.`Store` (
  `store_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  `postal_code` VARCHAR(45) NULL COMMENT '',
  `city` VARCHAR(45) NULL COMMENT '',
  `station_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`store_id`)  COMMENT '',
  INDEX `fk_Store_Station_idx` (`station_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Store_Station`
    FOREIGN KEY (`station_id`)
    REFERENCES `db_2`.`Station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_2`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_2`.`Item` (
  `item_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  `department` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`item_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_2`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_2`.`Inventory` (
  `iventory_id` INT NOT NULL COMMENT '',
  `item_id` INT NOT NULL COMMENT '',
  `store_id` INT NOT NULL COMMENT '',
  `timestamp` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`iventory_id`)  COMMENT '',
  INDEX `fk_Item_Store1_idx` (`store_id` ASC)  COMMENT '',
  INDEX `fk_Item_Product1_idx` (`item_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Item_Store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `db_2`.`Store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Product1`
    FOREIGN KEY (`item_id`)
    REFERENCES `db_2`.`Item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_2`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_2`.`Sale` (
  `sale_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sale_date` DATETIME NULL COMMENT '',
  `store_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`sale_id`)  COMMENT '',
  INDEX `fk_Sale_Store1_idx` (`store_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Sale_Store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `db_2`.`Store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_2`.`Weather Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_2`.`Weather Event` (
  `event_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NULL COMMENT '',
  `tmax` VARCHAR(45) NULL COMMENT '',
  `tmin` VARCHAR(45) NULL COMMENT '',
  `tavg` VARCHAR(45) NULL COMMENT '',
  `depart` VARCHAR(45) NULL COMMENT '',
  `dewpoint` VARCHAR(45) NULL COMMENT '',
  `wetbulb` VARCHAR(45) NULL COMMENT '',
  `heat` VARCHAR(45) NULL COMMENT '',
  `cool` VARCHAR(45) NULL COMMENT '',
  `sunrise` VARCHAR(45) NULL COMMENT '',
  `sunset` VARCHAR(45) NULL COMMENT '',
  `codesum` VARCHAR(45) NULL COMMENT '',
  `snowfall` VARCHAR(45) NULL COMMENT '',
  `preciptotal` VARCHAR(45) NULL COMMENT '',
  `stnpressure` VARCHAR(45) NULL COMMENT '',
  `sealevel` VARCHAR(45) NULL COMMENT '',
  `resultspeed` VARCHAR(45) NULL COMMENT '',
  `resultdir` VARCHAR(45) NULL COMMENT '',
  `avgspeed` VARCHAR(45) NULL COMMENT '',
  `station_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`event_id`)  COMMENT '',
  INDEX `fk_Weather_Station1_idx` (`station_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Weather_Station1`
    FOREIGN KEY (`station_id`)
    REFERENCES `db_2`.`Station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_2`.`Line_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_2`.`Line_Item` (
  `line_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sale_id` INT NOT NULL COMMENT '',
  `item_id` INT NOT NULL COMMENT '',
  `line_units` INT NULL COMMENT '',
  `line_price` DECIMAL(10,2) NULL COMMENT '',
  INDEX `fk_Item_has_Sale_Sale1_idx` (`sale_id` ASC)  COMMENT '',
  INDEX `fk_Order_Product1_idx` (`item_id` ASC)  COMMENT '',
  PRIMARY KEY (`line_id`)  COMMENT '',
  CONSTRAINT `fk_Item_has_Sale_Sale1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `db_2`.`Sale` (`sale_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Product1`
    FOREIGN KEY (`item_id`)
    REFERENCES `db_2`.`Item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
c