-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE hockey_players (
    player_id bigint,
    "firstName" text,
    "lastName" text,
    nationality text,
    "birthCity" text,
    "primaryPosition" text,
    "birthDate" text,
    link text
);